export const bankOptions = [
  { value: 'emiratesNbd', label: 'Emirates NBD' },
  { value: 'dubaiIslamicBank', label: 'Dubai Islamic Bank' },
  { value: 'adcb', label: 'Abu Dhabi Commercial Bank (ADCB)' },
  { value: 'mashreqBank', label: 'Mashreq Bank' },
  { value: 'emiratesIslamicBank', label: 'Emirates Islamic Bank' },
  { value: 'fab', label: 'First Abu Dhabi Bank (FAB)' },
  { value: 'rakbank', label: 'RAKBANK' },
  { value: 'cbd', label: 'Commercial Bank of Dubai (CBD)' },
  { value: 'standardCharteredUae', label: 'Standard Chartered UAE' },
  { value: 'hsbcUae', label: 'HSBC UAE' },
  { value: 'citibankUae', label: 'Citibank UAE' },
  { value: 'unitedArabBank', label: 'United Arab Bank' },
  { value: 'sharjahIslamicBank', label: 'Sharjah Islamic Bank' },
  { value: 'alHilalBank', label: 'Al Hilal Bank' },
  { value: 'adib', label: 'Abu Dhabi Islamic Bank (ADIB)' },
  { value: 'investBank', label: 'Invest Bank' },
  { value: 'nbf', label: 'National Bank of Fujairah' },
  { value: 'nbuaq', label: 'National Bank of Umm Al Qaiwain' },
  { value: 'bankOfSharjah', label: 'Bank of Sharjah' },
  { value: 'arabBankPlc', label: 'Arab Bank PLC' },
  { value: 'barclaysUae', label: 'Barclays Bank UAE' },
  { value: 'bnpParibasUae', label: 'BNP Paribas UAE' },
  { value: 'habibBank', label: 'Habib Bank Ltd.' },
  { value: 'bankOfBarodaUae', label: 'Bank of Baroda UAE' },
  { value: 'dohaBankUae', label: 'Doha Bank UAE' },
  { value: 'arabAfricanBank', label: 'Arab African International Bank' },
  { value: 'creditAgricoleUae', label: 'Credit Agricole UAE' },
  { value: 'alKhalijiFrance', label: 'Al Khaliji (France) S.A.' },
  { value: 'bankMelliIran', label: 'Bank Melli Iran' },
  { value: 'habibBankAgZurich', label: 'Habib Bank AG Zurich' },
  { value: 'sbiUae', label: 'State Bank of India (SBI) UAE' },
  { value: 'bankSaderatIran', label: 'Bank Saderat Iran' },
  { value: 'bankOfChinaDubai', label: 'Bank of China – Dubai Branch' },
  { value: 'iciciBankUae', label: 'ICICI Bank UAE' },
  { value: 'turkiyeIsBankasi', label: 'Turkiye Is Bankasi Dubai' }
];
